version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node12
jobs:
  node12:
    working_directory: ~/webserver-form-schema
    docker:
      - image: node:12.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
